### ISSUE TITLE
Fix the Hyperlink of "this guide"

### ISSUE THREAD

**Issue by teweitsai** [lsst-ts/ts_tma_tma-documentation_maintenance-documents_ni-linux-rt-installation#1]
Please help to fix the following hyperlink:

this guide --> https://readthedocs.web.cern.ch/display/MTA/%5BNILRT%5D+Virtual+Box+Host+Only+Adapter

Thanks!

**Comment by julen-garcia** [comment]
i can't find the link anymore

**Comment by teweitsai** [comment]
In this case, I guess we could only remove that hyperlink and close this issue. Thanks!
